### ISSUE TITLE
I QUIT! THIS CARD IS NOTHING BUT BROKEN!!!

### ISSUE THREAD

**Issue by Me-rn-rbh** [Joglacraft/7thbeatcards#4]
SPIN 2 WIN IS ONLY SUPPOSED TO ACTIVATE ON REROLL AND **WHEEL OF FORTUNE**, HOWEVER IT ACTIVATES ON **ANY CONSUMABLE!!!!** GRAAAAAAAA

**Comment by Joglacraft** [comment]
It should be fixed when 0.0.3 releases
