### ISSUE TITLE
Blueprint am I right 😔 

### ISSUE THREAD

**Issue by Me-rn-rbh** [Joglacraft/7thbeatcards#5]
So some cards don't work with blueprint, I get it.
HOWEVER, WHY DOES ONESHOT ONLY WORK WITH THE PART OF APPLYING THE MULT.
IT SHOULD ALSO WORK WITH THE GAINING MULT PART 🧼 
(this is actually useless cuz it still works the same but shhh)

**Comment by Joglacraft** [comment]
Works as intended (ish). Blueprint is meant to work when giving Xmult but not when adding it, as it results in the card getting several Xmults gains per hand played. The label is wrong, tho. I'll look into that.
