### ISSUE TITLE
Midspin bug that makes the card broken.

### ISSUE THREAD

**Issue by Me-rn-rbh** [Joglacraft/7thbeatcards#8]
Midspin should only gain mult on retriggering a card. Though, for some reason retriggering counts as upgrading a joker. Really anything that activates a joker in any way counts as retriggering so like yeah you get free mult.

**Comment by Joglacraft** [comment]
Perhaps you could send a video or tell me exactly how you did that so I can replicate it?

**Comment by Joglacraft** [comment]
After asking aroud a lot, I have concluded that there is no way to fix this issue, at least with my current skills. So for now midspin will be gated behind debug mode and not accessible by normal means.
